# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RMSHRentals' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    app_root = File.expand_path('..', __dir__)
    hermes_cli_path = File.join(
      app_root,
      'node_modules',
      'hermes-compiler',
      'hermesc',
      'osx-bin',
      'hermesc',
    )

    pods_target_support_files = File.join(
      __dir__,
      'Pods',
      'Target Support Files',
      'Pods-RMSHRentals',
      'Pods-RMSHRentals.*.xcconfig',
    )

    Dir.glob(pods_target_support_files).each do |xcconfig_path|
      xcconfig = File.read(xcconfig_path)
      hermes_setting = "HERMES_CLI_PATH = #{hermes_cli_path}"

      updated_xcconfig = if xcconfig.match?(/^HERMES_CLI_PATH = .+$/)
        xcconfig.gsub(/^HERMES_CLI_PATH = .+$/, hermes_setting)
      else
        "#{xcconfig.rstrip}\n#{hermes_setting}\n"
      end

      File.write(xcconfig_path, updated_xcconfig)
    end
  end
end
